### ISSUE TITLE
Solution for Fedora 35 with xfce and zsh

### ISSUE THREAD

**Issue by kiteloopdesign** [hrantzsch/vimclip#10]
Thanks for this wonderful idea. I was having issues with the gnome-terminal and eventually used command below, in case it can be of any help to someone

`/usr/bin/xfce4-terminal -x zsh -c 'vim'`

**Comment by kiteloopdesign** [comment]
Actually, that was not correct at all. I was just debugging and thought I had it figured out, but I do not. I am using this at the moment but not getting it right yet. Looks like $EDITOR is not pointing to vi but to nano, I could hardcode it on the script but lets see if I can figure it out ...

/usr/bin/xfce4-terminal -x bash -c '~/.local/bin/vimclip'

**Comment by kiteloopdesign** [comment]
Better but not there yet

`xfce4-terminal -e '/usr/bin/zsh -c "source .zshrc ; vimclip"'`

For some reason zsh is like it does not source its .rc file, and so I need to do it manually (otherwise $EDITOR is set to nano!). I am missing something for sure beacuse user is the correct one, and doing this

`xfce4-terminal -e '/usr/bin/zsh'` invokes the "usual" term with zsh, and $EDITOR is set to vim, etc.

**Comment by hrantzsch** [comment]
Hm, it _should_ not be that complicated. zsh should also source the rc file without explicitly being told to do so.
Just to double check, does `EDITOR=vim gnome-terminal -e vimclip` work as expected?

**Comment by kiteloopdesign** [comment]
Seems like gnome-terminal is not installed on XFCE, that's why I was using its equivalent, xfce-terminal.

In any case, I tried installing gnome-terminal, and it works straight away, no need to set EDITOR. So this is telling me that there is something going on here with respect to my `xfce-terminal`/zsh setup... More investigation needed ...

**Comment by hrantzsch** [comment]
I just re-read this and I realized that I completely missed you're invoking the shell and then vimclip inside of that. That should not be necessary, `xfce4-terminal -e vimclip` should be sufficient. Sorry about the confusion.
Feel free to reopen the issue if the problem persists.
