### ISSUE TITLE
Wayland compatibility

### ISSUE THREAD

**Issue by Mateiadrielrafael** [hrantzsch/vimclip#11]
Hi, does this project work on wayland? Don't know much about xsel, so I was just wondering.

**Comment by hrantzsch** [comment]
I've never tried it tbh, but I imagine you're right and xsel won't work. The common suggestion seems to be using wl-clipboard instead. We'd need to detect whether we're running on X or wayland and pick the appropriate one.

**Comment by hrantzsch** [comment]
Hey! While I haven't included "builtin" wayland support, you should now be able to set `VIMCLIP_CLIPBOARD_COMMAND` if xsel doesn't work for you. It looks like wl-clipboard is commonly used as a replacement for xsel. So if I'm reading the readme right, `VIMCLIP_CLIPBOARD_COMMAND=wc-copy vimclip` (with the vimclip version from master) should work.
If you try it out, please let me know if it really works.

**Comment by Mateiadrielrafael** [comment]
Thanks! Tried it and it works.

Right now my current setup does something like this:
```nix
pkgs.writeShellScriptBin "vimclip" ''
  if [ "wayland" = $XDG_SESSION_TYPE ]
  then
    export VIMCLIP_CLIPBOARD_COMMAND=${pkgs.wl-clipboard}/bin/wl-copy
  else
    export VIMCLIP_CLIPBOARD_COMMAND=${lib.getExe pkgs.xsel}
  fi

  ${lib.getExe vimclip}
''
```

Ignoring the nix fluff, I think something like this would be pretty easy to add to the actual script, right?

**Comment by Mateiadrielrafael** [comment]
I guess we can close this

**Comment by hrantzsch** [comment]
Great! I added the check for Wayland to the script as you suggested :+1:
