### ISSUE TITLE
Describe integration on macOS

### ISSUE THREAD

**Issue by hrantzsch** [hrantzsch/vimclip#3]
The integration section of the README is missing an explanation how to configure a shortcut to spawn vimscript in a new terminal on macOS.

**Comment by gnodar01** [comment]
I personally just have a simple applescript that I invoke with a hotkey:

```
tell application "iTerm"
    create window with default profile command "zsh -c $HOME/bin/vimclip"
end tell
```

For the hotkey, there's lots of programs like `skhd` that will let you set some up, but one can simply use the mac native Automator to create a service that runs an Apple Script and assign a keyboard shortcut to the service via System Preferences.

**Comment by hrantzsch** [comment]
Thanks for picking this up and for the instructions!
